"""
Utilities for converting CIFTI dense scalar maps (.dscalar.nii) into
Workbench cortical border files (.border).

The conversion is designed for surface-based cortical maps:

    .dscalar.nii -> L/R .func.gii metric -> binary ROI metric -> .border

Subcortical or volumetric CIFTI components are intentionally ignored because
Workbench .border files are surface features.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import numpy as np
import nibabel as nib

from .parcellation import _load_img, _get_gifti_array, _find_brainmodel_axis
from nibabel.cifti2.cifti2_axes import BrainModelAxis
from nibabel.cifti2 import Cifti2Image
from nibabel.cifti2.cifti2_axes import BrainModelAxis, ScalarAxis, SeriesAxis

from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Sequence

Hemisphere = Literal["L", "R", "both"]
DScalarBorderMode = Literal["pos", "neg", "abs", "range", "outside-range", "expr"]


@dataclass(frozen=True)
class DScalarToBorderResult:
    """Paths generated by :func:`dscalar_to_border`."""

    borders: tuple[Path, ...]
    workdir: Path
    expression: str


@dataclass(frozen=True)
class HemisphereSpec:
    """Workbench metadata for one cortical hemisphere."""

    key: Literal["L", "R"]
    structure: Literal["CORTEX_LEFT", "CORTEX_RIGHT"]
    surface: Path


def _run_cmd(cmd: Sequence[str | Path], *, dry_run: bool = False, verbose: bool = True) -> None:
    """Run one external command."""
    cmd_str = [str(x) for x in cmd]
    if verbose:
        print("\n[CMD]", " ".join(cmd_str))
    if not dry_run:
        subprocess.run(cmd_str, check=True)


def _require_file(path: str | Path | None, label: str) -> Path:
    """Return an absolute path after checking that the file exists."""
    if path is None:
        raise ValueError(f"{label} is required.")
    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise FileNotFoundError(f"{label} does not exist: {p}")
    return p


def build_dscalar_roi_expression(
    *,
    mode: DScalarBorderMode,
    threshold: float | None = None,
    lower: float | None = None,
    upper: float | None = None,
    inclusive: bool = False,
    expression: str | None = None,
) -> str:
    """
    Build a Workbench ``-metric-math`` expression using ``x`` as the metric variable.

    Parameters
    ----------
    mode
        ROI definition mode.
    threshold
        Threshold used by ``pos``, ``neg`` and ``abs`` modes.
    lower, upper
        Bounds used by ``range`` and ``outside-range`` modes.
    inclusive
        If True, use ``>=`` and ``<=`` instead of ``>`` and ``<``.
    expression
        Custom Workbench expression. Used only when ``mode='expr'``.

    Returns
    -------
    str
        A Workbench-compatible mathematical expression returning a binary ROI.
    """
    if mode == "expr":
        if not expression:
            raise ValueError("expression is required when mode='expr'.")
        return expression

    if expression is not None:
        return expression

    if mode == "pos":
        if threshold is None:
            raise ValueError("threshold is required when mode='pos'.")
        op = ">=" if inclusive else ">"
        return f"(x {op} {threshold})"

    if mode == "neg":
        if threshold is None:
            raise ValueError("threshold is required when mode='neg'.")
        neg_threshold = -abs(threshold) if threshold > 0 else threshold
        op = "<=" if inclusive else "<"
        return f"(x {op} {neg_threshold})"

    if mode == "abs":
        if threshold is None:
            raise ValueError("threshold is required when mode='abs'.")
        op = ">=" if inclusive else ">"
        return f"(abs(x) {op} {abs(threshold)})"

    if mode in {"range", "outside-range"}:
        if lower is None or upper is None:
            raise ValueError(f"lower and upper are required when mode='{mode}'.")
        if lower > upper:
            raise ValueError("lower must be <= upper.")

        if mode == "range":
            low_op = ">=" if inclusive else ">"
            high_op = "<=" if inclusive else "<"
            return f"(x {low_op} {lower} && x {high_op} {upper})"

        low_op = "<=" if inclusive else "<"
        high_op = ">=" if inclusive else ">"
        return f"(x {low_op} {lower} || x {high_op} {upper})"

    raise ValueError(f"Unknown mode: {mode}")


def _hemisphere_specs(
    *,
    hemi: Hemisphere,
    left_surface: str | Path | None,
    right_surface: str | Path | None,
) -> tuple[HemisphereSpec, ...]:
    """Return hemisphere-specific Workbench metadata."""
    specs: list[HemisphereSpec] = []

    if hemi in {"L", "both"}:
        specs.append(
            HemisphereSpec(
                key="L",
                structure="CORTEX_LEFT",
                surface=_require_file(left_surface, "left_surface"),
            )
        )

    if hemi in {"R", "both"}:
        specs.append(
            HemisphereSpec(
                key="R",
                structure="CORTEX_RIGHT",
                surface=_require_file(right_surface, "right_surface"),
            )
        )

    return tuple(specs)


def dscalar_to_border(
    dscalar: str | Path,
    out_prefix: str | Path,
    *,
    left_surface: str | Path | None = None,
    right_surface: str | Path | None = None,
    hemi: Hemisphere = "both",
    mode: DScalarBorderMode = "pos",
    threshold: float | None = None,
    lower: float | None = None,
    upper: float | None = None,
    inclusive: bool = False,
    expression: str | None = None,
    column: str | int | None = None,
    class_name: str = "dscalar_roi",
    placement: float = 0.33,
    fixnan: float = 0.0,
    workdir: str | Path | None = None,
    wb_command: str | Path = "wb_command",
    keep_intermediates: bool = False,
    dry_run: bool = False,
    verbose: bool = True,
) -> DScalarToBorderResult:
    """
    Convert a CIFTI dense scalar file to one or two Workbench border files.

    Parameters
    ----------
    dscalar
        Input ``.dscalar.nii`` file.
    out_prefix
        Output prefix. The function writes ``<out_prefix>.L.border`` and/or
        ``<out_prefix>.R.border``.
    left_surface, right_surface
        Hemisphere surface files, typically midthickness surfaces in the same
        mesh space as the CIFTI map.
    hemi
        Hemisphere(s) to process: ``'L'``, ``'R'`` or ``'both'``.
    mode
        ROI definition mode: ``pos``, ``neg``, ``abs``, ``range``,
        ``outside-range`` or ``expr``.
    threshold
        Threshold for ``pos``, ``neg`` and ``abs`` modes. For ``neg``, a
        positive value is interpreted as a negative threshold, e.g. ``2.3``
        means ``x < -2.3``.
    lower, upper
        Bounds for ``range`` and ``outside-range`` modes.
    inclusive
        Use closed inequalities when True.
    expression
        Custom Workbench expression using variable ``x``.
    column
        Optional CIFTI map column index or name.
    class_name
        Border class name stored in the generated ``.border`` files.
    placement
        Border placement fraction along each mesh edge.
    fixnan
        Value used to replace NaNs in ``-metric-math``.
    workdir
        Directory for intermediate metric/ROI files.
    wb_command
        Executable name or full path for Connectome Workbench ``wb_command``.
    keep_intermediates
        Keep intermediate GIFTI metric files.
    dry_run
        Print commands without executing them.
    verbose
        Print executed commands and summary information.

    Returns
    -------
    DScalarToBorderResult
        Generated border paths, work directory and ROI expression.
    """
    wb = shutil.which(str(wb_command)) if str(wb_command) == "wb_command" else str(wb_command)
    if wb is None:
        raise RuntimeError("Cannot find wb_command. Provide its full path via wb_command=...")

    dscalar_path = _require_file(dscalar, "dscalar")
    out_prefix_path = Path(out_prefix).expanduser().resolve()
    out_prefix_path.parent.mkdir(parents=True, exist_ok=True)

    workdir_path = (
        Path(workdir).expanduser().resolve()
        if workdir is not None
        else out_prefix_path.parent / f"{out_prefix_path.name}_work"
    )
    workdir_path.mkdir(parents=True, exist_ok=True)

    roi_expression = build_dscalar_roi_expression(
        mode=mode,
        threshold=threshold,
        lower=lower,
        upper=upper,
        inclusive=inclusive,
        expression=expression,
    )
    hemispheres = _hemisphere_specs(
        hemi=hemi,
        left_surface=left_surface,
        right_surface=right_surface,
    )

    if verbose:
        print(f"\nInput dscalar: {dscalar_path}")
        print(f"ROI expression: {roi_expression}")
        print(f"Work directory: {workdir_path}")

    borders: list[Path] = []
    intermediate_files: list[Path] = []

    for spec in hemispheres:
        metric = workdir_path / f"{out_prefix_path.name}.{spec.key}.func.gii"
        roi_metric = workdir_path / f"{out_prefix_path.name}.{spec.key}.roi.func.gii"
        border = out_prefix_path.parent / f"{out_prefix_path.name}.{spec.key}.border"

        _run_cmd(
            [wb, "-cifti-separate", dscalar_path, "COLUMN", "-metric", spec.structure, metric],
            dry_run=dry_run,
            verbose=verbose,
        )

        var_args: list[str | Path] = ["-var", "x", metric]
        if column is not None:
            var_args += ["-column", str(column)]

        _run_cmd(
            [wb, "-metric-math", roi_expression, roi_metric, "-fixnan", str(fixnan), *var_args],
            dry_run=dry_run,
            verbose=verbose,
        )

        _run_cmd(
            [
                wb,
                "-metric-rois-to-border",
                spec.surface,
                roi_metric,
                class_name,
                border,
                "-placement",
                str(placement),
            ],
            dry_run=dry_run,
            verbose=verbose,
        )

        borders.append(border)
        intermediate_files.extend([metric, roi_metric])

    if not keep_intermediates and not dry_run:
        for f in intermediate_files:
            f.unlink(missing_ok=True)
        try:
            workdir_path.rmdir()
        except OSError:
            pass

    if verbose:
        print("\nDone. Border files:")
        for border in borders:
            print(f"  {border}")

    return DScalarToBorderResult(
        borders=tuple(borders),
        workdir=workdir_path,
        expression=roi_expression,
    )


def cifti_to_gifti(
    cifti_file,
    output_dir=None,
    output_prefix=None,
    fill_value=np.nan,
    save=True,
    dtype=np.float32,
):
    """
    Convert cortical data in a CIFTI .dscalar.nii or .dtseries.nii file
    into left and right hemisphere GIFTI files.

    Parameters
    ----------
    cifti_file : str, Path, or nib.Cifti2Image
        Input CIFTI image, usually .dscalar.nii or .dtseries.nii.

    output_dir : str, Path, or None
        Directory to save output GIFTI files. If None, use the directory
        of cifti_file when cifti_file is a path, otherwise use current directory.

    output_prefix : str or None
        Prefix for output files. If None, inferred from cifti filename.

    fill_value : float
        Value assigned to vertices not present in the CIFTI BrainModelAxis,
        usually medial wall vertices. Default is np.nan.

    save : bool
        If True, save GIFTI files to disk.

    dtype : numpy dtype
        Output data type.

    Returns
    -------
    result : dict
        Dictionary containing:
            "L_img" : left hemisphere GiftiImage or None
            "R_img" : right hemisphere GiftiImage or None
            "L_file" : saved left hemisphere filepath or None
            "R_file" : saved right hemisphere filepath or None
            "data_shape" : original CIFTI data shape
            "n_maps" : number of maps or time points
    """
    # Load CIFTI image
    if isinstance(cifti_file, (str, Path)):
        cifti_path = Path(cifti_file)
        img = nib.load(str(cifti_path))
    else:
        cifti_path = None
        img = cifti_file

    if not isinstance(img, nib.Cifti2Image):
        raise TypeError("Input must be a CIFTI image or a path to a CIFTI file.")

    # Find BrainModelAxis
    axes = [img.header.get_axis(i) for i in range(len(img.shape))]

    brain_axis_index = None
    brain_axis = None

    for i, axis in enumerate(axes):
        if isinstance(axis, BrainModelAxis):
            brain_axis_index = i
            brain_axis = axis
            break

    if brain_axis is None:
        raise ValueError("No BrainModelAxis found in the input CIFTI file.")

    # Move brain axis to the last dimension
    data = np.asarray(img.get_fdata())
    data = np.moveaxis(data, brain_axis_index, -1)

    n_grayordinates = data.shape[-1]
    nonbrain_shape = data.shape[:-1]

    if len(nonbrain_shape) == 0:
        data_2d = data.reshape(1, n_grayordinates)
    else:
        data_2d = data.reshape(-1, n_grayordinates)

    n_maps = data_2d.shape[0]

    # Prepare output
    hemi_data = {
        "L": None,
        "R": None,
    }

    structure_to_hemi = {
        "CIFTI_STRUCTURE_CORTEX_LEFT": "L",
        "CIFTI_STRUCTURE_CORTEX_RIGHT": "R",
    }

    # brain_axis.iter_structures() yields:
    # structure_name, cifti_slice, sub_brain_model_axis
    for structure_name, cifti_slice, sub_axis in brain_axis.iter_structures():
        if structure_name not in structure_to_hemi:
            continue

        hemi = structure_to_hemi[structure_name]

        if structure_name not in brain_axis.nvertices:
            raise ValueError(
                f"Cannot determine total number of vertices for {structure_name}."
            )

        n_vertices = brain_axis.nvertices[structure_name]

        out = np.full(
            (n_maps, n_vertices),
            fill_value,
            dtype=dtype,
        )

        # sub_axis.vertex gives surface vertex indices included in the CIFTI file
        vertices = np.asarray(sub_axis.vertex)

        if vertices.size != data_2d[:, cifti_slice].shape[1]:
            raise ValueError(
                f"Vertex index length does not match data length for {structure_name}."
            )

        out[:, vertices] = data_2d[:, cifti_slice].astype(dtype)

        hemi_data[hemi] = out

    def _make_gifti_from_matrix(matrix):
        """
        Create a GIFTI image from a matrix with shape:
            n_maps x n_vertices

        Each map/time point is saved as one GIFTI data array.
        """
        if matrix is None:
            return None

        gii = nib.GiftiImage()

        for i in range(matrix.shape[0]):
            arr = nib.gifti.GiftiDataArray(
                data=matrix[i].astype(dtype)
            )
            gii.add_gifti_data_array(arr)

        return gii

    L_img = _make_gifti_from_matrix(hemi_data["L"])
    R_img = _make_gifti_from_matrix(hemi_data["R"])

    L_file = None
    R_file = None

    if save:
        if output_dir is None:
            if cifti_path is not None:
                output_dir = cifti_path.parent
            else:
                output_dir = Path(".")
        else:
            output_dir = Path(output_dir)

        output_dir.mkdir(parents=True, exist_ok=True)

        if output_prefix is None:
            if cifti_path is not None:
                name = cifti_path.name
                for suffix in [".dscalar.nii", ".dtseries.nii", ".nii"]:
                    if name.endswith(suffix):
                        name = name[: -len(suffix)]
                        break
                output_prefix = name
            else:
                output_prefix = "converted_cifti"

        if L_img is not None:
            L_file = output_dir / f"{output_prefix}.L.func.gii"
            nib.save(L_img, str(L_file))

        if R_img is not None:
            R_file = output_dir / f"{output_prefix}.R.func.gii"
            nib.save(R_img, str(R_file))

    result = {
        "L_img": L_img,
        "R_img": R_img,
        "L_file": str(L_file) if L_file is not None else None,
        "R_file": str(R_file) if R_file is not None else None,
        "data_shape": img.shape,
        "n_maps": n_maps,
        "brain_axis_index": brain_axis_index,
        "fill_value": fill_value,
    }

    return result


def _get_gifti_matrix(gifti_img):
    """
    Extract GIFTI data as a matrix with shape:
        n_maps x n_vertices

    For a single-array GIFTI:
        output shape = 1 x n_vertices

    For a multi-array GIFTI:
        output shape = n_arrays x n_vertices
    """
    img = _load_img(gifti_img)

    if not isinstance(img, nib.GiftiImage):
        raise TypeError("Expected a GIFTI image or a GIFTI filepath.")

    arrays = [np.asarray(d.data) for d in img.darrays]

    if len(arrays) == 0:
        raise ValueError("The GIFTI image contains no data arrays.")

    arrays = [np.asarray(a).squeeze() for a in arrays]

    for a in arrays:
        if a.ndim != 1:
            raise ValueError(
                "Each GIFTI data array must be 1D. "
                "If your GIFTI stores vertices x maps in one array, "
                "split it into separate data arrays first."
            )

    n_vertices = arrays[0].shape[0]

    if not all(a.shape[0] == n_vertices for a in arrays):
        raise ValueError("All GIFTI data arrays must have the same number of vertices.")

    matrix = np.vstack(arrays)

    return matrix


def _make_output_axis(
    n_maps,
    output_type="dscalar",
    scalar_names=None,
    series_start=0.0,
    series_step=1.0,
    series_unit="SECOND",
):
    """
    Create the non-brain CIFTI axis.

    Parameters
    ----------
    n_maps : int
        Number of maps or time points.

    output_type : {"dscalar", "dtseries"}
        Output CIFTI style.

    scalar_names : list[str] or None
        Names for scalar maps when output_type == "dscalar".

    series_start : float
        Start time for dtseries output.

    series_step : float
        Time step for dtseries output.

    series_unit : str
        Time unit for dtseries output.

    Returns
    -------
    axis : ScalarAxis or SeriesAxis
    """
    if output_type == "dscalar":
        if scalar_names is None:
            scalar_names = [f"map_{i + 1}" for i in range(n_maps)]

        if len(scalar_names) != n_maps:
            raise ValueError("Length of scalar_names must match n_maps.")

        return ScalarAxis(scalar_names)

    if output_type == "dtseries":
        return SeriesAxis(
            start=series_start,
            step=series_step,
            size=n_maps,
            unit=series_unit,
        )

    raise ValueError("output_type must be either 'dscalar' or 'dtseries'.")


def gifti_to_cifti(
    lh_gifti,
    rh_gifti,
    template_cifti,
    output_file=None,
    output_type="dscalar",
    fill_value=np.nan,
    scalar_names=None,
    series_start=0.0,
    series_step=1.0,
    series_unit="SECOND",
    dtype=np.float32,
):
    """
    Convert left/right hemisphere GIFTI files to a CIFTI image using a
    template CIFTI BrainModelAxis.

    Parameters
    ----------
    lh_gifti : str, Path, nib.GiftiImage, or None
        Left hemisphere GIFTI data.

    rh_gifti : str, Path, nib.GiftiImage, or None
        Right hemisphere GIFTI data.

    template_cifti : str, Path, or nib.Cifti2Image
        Template CIFTI image. Its BrainModelAxis defines the target CIFTI
        grayordinate space and vertex mapping.

    output_file : str, Path, or None
        If provided, save the output CIFTI image to this path.

    output_type : {"dscalar", "dtseries"}
        Output CIFTI style.

        "dscalar":
            output shape = n_maps x n_grayordinates

        "dtseries":
            output shape = n_timepoints x n_grayordinates

    fill_value : float
        Value assigned to non-cortical grayordinates, usually subcortex,
        or to cortical vertices absent from the input GIFTI.

    scalar_names : list[str] or None
        Names for maps when output_type == "dscalar".

    series_start : float
        Start time for dtseries output.

    series_step : float
        Time step for dtseries output.

    series_unit : str
        Time unit for dtseries output.

    dtype : numpy dtype
        Output data type.

    Returns
    -------
    cifti_img : nib.Cifti2Image
        Output CIFTI image.

    info : dict
        Summary information, including number of maps, grayordinates, and
        inserted cortical structures.

    Notes
    -----
    This function does not perform surface resampling. The GIFTI files must
    already match the cortical vertex space of the template CIFTI.

    For example, if the template CIFTI is fsLR 32k, the input GIFTI files
    should also be fsLR 32k with the same vertex indexing.
    """
    if lh_gifti is None and rh_gifti is None:
        raise ValueError("At least one of lh_gifti or rh_gifti must be provided.")

    template_img = _load_img(template_cifti)
    _, brain_axis = _find_brainmodel_axis(template_img)

    lh_matrix = None
    rh_matrix = None

    if lh_gifti is not None:
        lh_matrix = _get_gifti_matrix(lh_gifti)

    if rh_gifti is not None:
        rh_matrix = _get_gifti_matrix(rh_gifti)

    n_maps = None

    if lh_matrix is not None:
        n_maps = lh_matrix.shape[0]

    if rh_matrix is not None:
        if n_maps is None:
            n_maps = rh_matrix.shape[0]
        elif rh_matrix.shape[0] != n_maps:
            raise ValueError(
                "Left and right GIFTI files must have the same number of "
                "maps/data arrays."
            )

    n_grayordinates = len(brain_axis)

    cifti_data = np.full(
        (n_maps, n_grayordinates),
        fill_value,
        dtype=dtype,
    )

    structure_to_matrix = {
        "CIFTI_STRUCTURE_CORTEX_LEFT": lh_matrix,
        "CIFTI_STRUCTURE_CORTEX_RIGHT": rh_matrix,
    }

    inserted_structures = {}

    for structure_name, cifti_slice, sub_axis in brain_axis.iter_structures():
        if structure_name not in structure_to_matrix:
            continue

        matrix = structure_to_matrix[structure_name]

        if matrix is None:
            continue

        if structure_name not in brain_axis.nvertices:
            raise ValueError(
                f"Template CIFTI does not report total vertex count for "
                f"{structure_name}."
            )

        n_vertices_template = brain_axis.nvertices[structure_name]
        n_vertices_input = matrix.shape[1]

        if n_vertices_input != n_vertices_template:
            raise ValueError(
                f"{structure_name} vertex count mismatch: "
                f"input GIFTI has {n_vertices_input} vertices, "
                f"but template CIFTI expects {n_vertices_template} vertices. "
                "You likely need surface resampling before conversion."
            )

        vertices = np.asarray(sub_axis.vertex)

        if len(vertices) != len(range(*cifti_slice.indices(n_grayordinates))):
            raise ValueError(
                f"Vertex index length does not match CIFTI slice length for "
                f"{structure_name}."
            )

        cifti_data[:, cifti_slice] = matrix[:, vertices].astype(dtype)

        def _safe_int_or_none(x):
            """Convert x to int if x is not None."""
            return int(x) if x is not None else None

        inserted_structures[structure_name] = {
            "n_vertices_input": int(n_vertices_input),
            "n_vertices_inserted": int(len(vertices)),
            "cifti_slice": (
                _safe_int_or_none(cifti_slice.start),
                _safe_int_or_none(cifti_slice.stop),
                _safe_int_or_none(cifti_slice.step),
            ),
        }

    output_axis = _make_output_axis(
        n_maps=n_maps,
        output_type=output_type,
        scalar_names=scalar_names,
        series_start=series_start,
        series_step=series_step,
        series_unit=series_unit,
    )

    cifti_img = Cifti2Image(
        dataobj=cifti_data,
        header=(output_axis, brain_axis),
    )

    info = {
        "output_type": output_type,
        "n_maps": int(n_maps),
        "n_grayordinates": int(n_grayordinates),
        "fill_value": fill_value,
        "inserted_structures": inserted_structures,
        "nvertices": dict(brain_axis.nvertices),
    }

    if output_file is not None:
        nib.save(cifti_img, str(output_file))

    return cifti_img, info


def build_arg_parser() -> argparse.ArgumentParser:
    """Build the command-line parser used by the console entry point."""
    parser = argparse.ArgumentParser(
        description="Convert a .dscalar.nii map to left/right .border files via Workbench."
    )

    parser.add_argument("--dscalar", required=True, help="Input .dscalar.nii file.")
    parser.add_argument("--left-surf", dest="left_surface", help="Left hemisphere surface file.")
    parser.add_argument("--right-surf", dest="right_surface", help="Right hemisphere surface file.")
    parser.add_argument("--out-prefix", required=True, help="Output prefix, e.g. results/my_roi.")
    parser.add_argument("--workdir", default=None, help="Working directory for intermediate files.")
    parser.add_argument("--wb-command", default="wb_command", help="Path to wb_command.")
    parser.add_argument("--hemi", choices=["L", "R", "both"], default="both", help="Hemisphere(s) to process.")
    parser.add_argument("--column", default=None, help="Optional dscalar map column number or name.")
    parser.add_argument("--class-name", default="dscalar_roi", help="Class name stored in border files.")
    parser.add_argument("--placement", type=float, default=0.33, help="Border placement fraction along mesh edge.")
    parser.add_argument("--fixnan", type=float, default=0.0, help="Replace NaN with this value during metric-math.")
    parser.add_argument("--keep-intermediates", action="store_true", help="Keep separated metric and ROI metric files.")
    parser.add_argument("--dry-run", action="store_true", help="Print commands without running them.")
    parser.add_argument("--quiet", action="store_true", help="Suppress progress output except Workbench errors.")

    parser.add_argument(
        "--mode",
        choices=["pos", "neg", "abs", "range", "outside-range", "expr"],
        required=True,
        help=(
            "ROI mode: pos=x>thr, neg=x<-abs(thr), abs=abs(x)>thr, "
            "range=lower<x<upper, outside-range=x<lower or x>upper, expr=custom expression."
        ),
    )
    parser.add_argument("--thr", dest="threshold", type=float, help="Threshold for pos/neg/abs modes.")
    parser.add_argument("--lower", type=float, help="Lower bound for range modes.")
    parser.add_argument("--upper", type=float, help="Upper bound for range modes.")
    parser.add_argument("--inclusive", action="store_true", help="Use >= and <= instead of > and <.")
    parser.add_argument(
        "--expr",
        dest="expression",
        default=None,
        help="Custom wb_command -metric-math expression using variable x, e.g. '(x > 2.3 || x < -2.3)'.",
    )

    return parser


def main(argv: Sequence[str] | None = None) -> DScalarToBorderResult:
    """Console entry point."""
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    return dscalar_to_border(verbose=not args.quiet, **vars(args))


__all__ = [
    "DScalarBorderMode",
    "DScalarToBorderResult",
    "Hemisphere",
    "build_dscalar_roi_expression",
    "dscalar_to_border",
    "build_arg_parser",
    "main",
]
